import Header from "@/components/molecules/header/Header";
import ModalManager from "@/components/organisms/modals/ModalManager";
import ModalState from "@/context/modal/modal.provider";
import ToastState from "@/context/toast/toast.provider";
import { Web3Provider } from "@/context/web3provider/web3.provider";
import ThemeRegistry from "@/themes/ThemeRegistry";
import { Box } from "@mui/material";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import ParticlesBackground from "@/components/atoms/ParticlesBackground";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className} style={{ margin: 0 }}>
        <ThemeRegistry>
          <Web3Provider>
            <ModalState>
              <ToastState>
                <Header />

                <Box component="main" p={4}>
                  <ParticlesBackground />

                  {children}
                </Box>
                <ModalManager />
              </ToastState>
            </ModalState>
          </Web3Provider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
